version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: